### ISSUE TITLE
fsm json hangs when loading...

### ISSUE THREAD

**Issue by kkemple** [adrianco/spigo#17]
Need to understand what is causing this hang up and get a fix in place

**Comment by adrianco** [comment]
fsm.json was missing the node definitions, only had edges. Now fixed in the latest update. Please retest, as it doesn't want to load in the SPA.

**Comment by kkemple** [comment]
ah okay, I will update to use new fsm json, i will test and verif, then close this ticket

**Comment by adrianco** [comment]
Looks good now
