### ISSUE TITLE
Generate deeper hierarchy for containers and sysdig

### ISSUE THREAD

**Issue by adrianco** [adrianco/spigo#29]
Sysdig https://github.com/draios/sysdig interfaces to Sysdig Cloud which has a zoomable service view that can show machines, vms, containers and processes
https://dl.dropboxusercontent.com/u/16649518/2015-06-11-monitorama.pptx

To model this in spigo, need to expand the "service" to instance + container + process for cloud, and machine + VM + container + process for on prem models.

**Comment by hubayirp** [comment]
Nice find - good to add.

**Comment by adrianco** [comment]
First phase done, names package now has definitions for container and process, and new MakeContainer function. Need to change architecture package next to allow containers to be specified.

**Comment by adrianco** [comment]
Names now extended to include container hierarchy as default, with configurable filter to hide the extra levels when not being used. All json output files have been re-generated with the new naming scheme.

**Comment by hubayirp** [comment]
Good it's cofigurable - CIFS will have a problem

**Comment by adrianco** [comment]
The filter is just for what gets sent to the json file for visualization, the simulation can have as much detail as it needs for generating monitoring output for a specific tool.

**Comment by adrianco** [comment]
Filtering and naming is managed in names.go
Filtering occurs centrally in edda.go before calling graphjson.go to log the node or edge

**Comment by adrianco** [comment]
architecture format updated, new simple container architecture created, build.sh and run.sh used to regenerate all the output files. Code synced.
