### ISSUE TITLE
UI Architecture menu needs more entries or dynamic update

### ISSUE THREAD

**Issue by adrianco** [adrianco/spigo#42]
There are only four entries in the Menu, but several additional architecture output files exist.

Need to document how to add entries to the list or make it dynamic based on whatever is available.

$ ls json
aws_ac_ra_web.json	fsm3.json		lamp5.json		migration3.json		netflix1.json		netflix9.json		netflixoss7.json
container.json		fsm4.json		lamp6.json		migration4.json		netflix2.json		netflixoss.json		netflixoss8.json
container1.json		fsm5.json		lamp7.json		migration5.json		netflix3.json		netflixoss1.json	netflixoss9.json
container2.json		lamp.json		lamp8.json		migration6.json		netflix4.json		netflixoss2.json	testyaml.json
container3.json		lamp1.json		lamp9.json		migration7.json		netflix5.json		netflixoss3.json
fsm.json		lamp2.json		migration.json		migration8.json		netflix6.json		netflixoss4.json
fsm1.json		lamp3.json		migration1.json		migration9.json		netflix7.json		netflixoss5.json
fsm2.json		lamp4.json		migration2.json		netflix.json		netflix8.json		netflixoss6.json

**Comment by kkemple** [comment]
i have updated control to include other architectures in PR #43, however in order to make it dynamic we will need some type of config file that lists at least the architecture types (and ideally count for each one). Right now there is no way to discern what JSON is available from the client app.

**Comment by adrianco** [comment]
OK, just needed to know where to change it, looks like an easy update to ui/js/toolbar/index.js

Thanks

**Comment by kkemple** [comment]
oh sure, yeah very easy to do manually :smile:

**Comment by hubayirp** [comment]
+1

Good luck with oscon training..
