### ISSUE TITLE
Unable to build locally

### ISSUE THREAD

**Issue by hvram1** [adrianco/spigo#52]
I tried to use the compose2arch program on Linux-x64 and it expectedly failed . I tried to compile the compile2arch.go by setting the GOPATH but the directory structure is not right . Is there a easier way to build this code ?

**Comment by adrianco** [comment]
I don't have linux to test on, but I suspect that you need to go get the gopkg.in/yaml.v2 package in order to get the compose package to build, then compose2arch should build too.

Try using go test in the compose package to make sure it's working right before you build compose2arch

**Comment by hvram1** [comment]
This is what I get

vagrant@packer-virtualbox-iso-1441376200:~/spigo/compose2arch$ go test
compose2arch.go:6:2: cannot find package "github.com/adrianco/spigo/compose"
in any of:
        /home/vagrant/go/src/github.com/adrianco/spigo/compose (from
$GOROOT)
        /home/vagrant/spigo/src/github.com/adrianco/spigo/compose (from
$GOPATH)

On Tue, Sep 15, 2015 at 10:06 PM, Adrian Cockcroft <notifications@github.com

**Comment by hvram1** [comment]
Sorry I was new to go and did not realize how picky it is about the source paths .  had to put the git clone into the directory structure that GOPATH wanted . That fixed the issue
