### ISSUE TITLE
Generate Neo4j cypher format graph

### ISSUE THREAD

**Issue by adrianco** [adrianco/spigo#65]
Fork the graphjson package and change to generate cypher
Modify the collect code to log zipkin trace data in Neo4j as well
Add -n <http://localhost:7474> option to enable, with default local connection

**Comment by adrianco** [comment]
Example Cypher create

```
create 
        (lamp_mysql00:Node {name:"lamp.us-east-1.zoneA.rds-mysql00", package:"store", timestamp:"2016-04-17T13:40:05.938437713-07:00",metadata:"IP/54.198.0.1", region:"us-east-1", zone: "zoneA"}),
        (lamp_mysql01:Node {name:"lamp.us-east-1.zoneA.rds-mysql01", package:"store", timestamp:"2016-04-17T13:40:05.938513762-07:00",metadata:"IP/54.221.0.1", region:"us-east-1", zone: "zoneA"}),
        lamp_mysql00-[:CONNECTION]->lamp_mysql01;
```

**Comment by adrianco** [comment]
Result of above query
![screen shot 2016-04-29 at 5 19 29 pm](https://cloud.githubusercontent.com/assets/111700/14920609/b4b1ecf6-0e2e-11e6-93b7-5a0fd109f1ab.png)

**Comment by hubayirp** [comment]
nice!

**Comment by adrianco** [comment]
Checked in first attempt at a neo4j driver, go test does write to Neo4j now, much more to do.

**Comment by adrianco** [comment]
Got the basics implemented. Now adding flow records.

**Comment by adrianco** [comment]
Worked with Michael Hunger to fix the way I was storing the data, made it easier to query. Basic setup is done so closing this issue and continuing work on others.
