### ISSUE TITLE
Question on F5 LB and Zuul

### ISSUE THREAD

**Issue by rbkumar88** [adrianco/spigo#66]
Hi Adrian,

I have a question on configuring Zuul and exposing the same with multiple host names.

Currently we have apache mod jk reverse proxy to do that.

I am sure this is not the right forum/place to ask the same. Please let me know where can I post this to get it answered from you.

Thanks
Bharath

**Comment by hubayirp** [comment]
+1

**Comment by adrianco** [comment]
This isn't a spigo related question, you should look at https://github.com/netflix/zuul
