### ISSUE TITLE
PDF referenced in README is missing

### ISSUE THREAD

**Issue by dtzWill** [adrianco/spigo#69]
In the current README:

"See this paper for some Occam code and results for the original version of this idea circa 2007."

includes a link to a file

"SkypeSim07.pdf"

that doesn't exist.

Is this paper still available? If not, probably should remove this line from the README :).

**Comment by adrianco** [comment]
It's there on my local copy but I'm having trouble getting github to sync it. It got lost when I created a directory hierarchy

**Comment by adrianco** [comment]
For some reason I don't understand, github deletes the file whenever I put it in a subdirectory but it's OK at the top level, so I moved it back to top level and changed the link. Should view ok now. Thanks for pointing out the problem!
