### ISSUE TITLE
Building after a fork

### ISSUE THREAD

**Issue by hvandenb** [adrianco/spigo#70]
What's the best way of building the project with go when you have forked the project? It seems to have issues with finding the packages that are within the local directory. The GO* variables are all setup, but using **go build** in the root keep failing.

My go build keeps failing with the packages local. I can use **go get** to get the packages but that just places them in those directories. I'd like to make improvements to the packages. 

Here's an example
```
../../adrianco/spigo/actors/edda/edda.go:5:2: cannot find package "github.com/adrianco/spigo/tooling/archaius" in any of:
    /Users/me/tools/go/src/github.com/adrianco/spigo/tooling/archaius (from $GOROOT)
    /Users/me/projects/gocode/src/github.com/adrianco/spigo/tooling/archaius (from $GOPATH)
```

Settings:
```
GOROOT=/Users/me/tools/go
GOPATH=/Users/me/projects/gocode
```

**Comment by adrianco** [comment]
I'm not sure how to handle this. When I was working with a modified fork of someone elses code I manually changed the includes to reference it.

**Comment by hvandenb** [comment]
I'll give that a shot. It seems to be an as designed limitation in go.

**Comment by hubayirp** [comment]
This might help -
http://code.openark.org/blog/development/forking-golang-repositories-on-github-and-managing-the-import-path

On Wed, Jun 1, 2016 at 8:56 PM, Henri van den Bulk <notifications@github.com

**Comment by hvandenb** [comment]
Thanks @hubayirp that's a great help. Closing issue.
